
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 22100
 */
public class T10kampaamo extends javax.swing.JFrame {

    /**
     * Creates new form T10kampaamo
     */
    public T10kampaamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jRbtAikuiset = new javax.swing.JRadioButton();
        jRbtLapset = new javax.swing.JRadioButton();
        jRbtLyhyet = new javax.swing.JRadioButton();
        jRbtKeskipitkat = new javax.swing.JRadioButton();
        jRbtPitkat = new javax.swing.JRadioButton();
        jCBraidat = new javax.swing.JCheckBox();
        jTxtFvalinnat = new javax.swing.JTextField();
        jCBtyvivari = new javax.swing.JCheckBox();
        jCBkoko = new javax.swing.JCheckBox();
        jCBjuhla = new javax.swing.JCheckBox();
        jCBkoe = new javax.swing.JCheckBox();
        jCBpesu = new javax.swing.JCheckBox();
        jCBkiharrus = new javax.swing.JCheckBox();
        jCBpermanentti = new javax.swing.JCheckBox();
        jCBnetti = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jSpnMaara = new javax.swing.JSpinner();
        jLblhlo = new javax.swing.JLabel();
        jLblPituus = new javax.swing.JLabel();

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRbtAikuiset);
        jRbtAikuiset.setText("Aikuiset 25 €");
        jRbtAikuiset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtAikuisetActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbtLapset);
        jRbtLapset.setText("Lapset 15 €");

        buttonGroup2.add(jRbtLyhyet);
        jRbtLyhyet.setText("Lyhyet 0 €");

        buttonGroup2.add(jRbtKeskipitkat);
        jRbtKeskipitkat.setText("Keskipitkät 5 €");

        buttonGroup2.add(jRbtPitkat);
        jRbtPitkat.setText("Pitkät 10 €");

        jCBraidat.setText("Raidat 30 €");
        jCBraidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBraidatActionPerformed(evt);
            }
        });

        jTxtFvalinnat.setText("Valitse palvelut");

        jCBtyvivari.setText("Tyviväri 30 €");

        jCBkoko.setText("Koko pään värjäys 80 €");

        jCBjuhla.setText("Juhlakampaus 50 €");

        jCBkoe.setText("Koekampaus 20 €");

        jCBpesu.setText("Pesu 10 €");

        jCBkiharrus.setText("Kiharrus 15 €");

        jCBpermanentti.setText("Permanentti 50 €");

        jCBnetti.setForeground(new java.awt.Color(102, 0, 204));
        jCBnetti.setText("Internet-varauksella saa - 5 eur alennuksen, jos kokonaissumma on 25 eur tai enemmän.");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Osta palvelut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        jLblhlo.setText("Henkilömäärä");

        jLblPituus.setText("Valitse hiusten pituus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRbtLyhyet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRbtKeskipitkat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(jRbtPitkat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jCBkoe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jCBjuhla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                                .addComponent(jCBkoko)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jCBpermanentti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jCBkiharrus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jCBraidat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCBtyvivari, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCBpesu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxtFvalinnat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jCBnetti, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRbtAikuiset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jRbtLapset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpnMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblhlo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLblPituus, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblhlo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbtAikuiset)
                    .addComponent(jRbtLapset)
                    .addComponent(jSpnMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLblPituus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRbtLyhyet)
                        .addComponent(jRbtKeskipitkat))
                    .addComponent(jRbtPitkat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTxtFvalinnat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jCBraidat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBtyvivari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBkoko)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(16, 16, 16)))
                        .addComponent(jCBjuhla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBkoe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBpesu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBkiharrus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBpermanentti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jCBnetti, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRbtAikuisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtAikuisetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbtAikuisetActionPerformed

    private void jCBraidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBraidatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBraidatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

     DefaultListModel dlm = new DefaultListModel();
        
        int maara = (Integer) jSpnMaara.getValue();
        double total;
        double i;
        int a;
        

        
        jRbtAikuiset.setActionCommand("Aikuiset");
        jRbtLapset.setActionCommand("Lapset");
        
        jRbtLyhyet.setActionCommand("Lyhyet");
        jRbtKeskipitkat.setActionCommand("Keskipitkät");
        jRbtPitkat.setActionCommand("Pitkät");
        

        if("Aikuiset".equals(buttonGroup1.getSelection().getActionCommand())) {
            a = 25;
                if("Keskipitkät".equals(buttonGroup2.getSelection().getActionCommand())){
                    i = a + 5;
                    if(jCBraidat.isSelected()){
                        i += 30; 
                    }
                    if(jCBtyvivari.isSelected()){
                        i += 30;     
                    }
                    if(jCBkoko.isSelected()){
                        i += 80;                          
                    }
                    if(jCBjuhla.isSelected()){
                        i += 50;
                    }
                    if(jCBkoe.isSelected()){
                        i += 20;                          
                    }
                    if(jCBpesu.isSelected()){
                        i += 10;                          
                    }
                    if(jCBkiharrus.isSelected()){
                        i += 15;                          
                    }
                    if(jCBpermanentti.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jCBnetti.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Henkilömäärä " + maara + " " + "\n" + "Loppusumma: " + total + " €"); 
                }
                if("Pitkät".equals(buttonGroup2.getSelection().getActionCommand())){
                    i = a + 10;
                    if(jCBraidat.isSelected()){
                        i += 30; 
                    }
                    if(jCBtyvivari.isSelected()){
                        i += 30;     
                    }
                    if(jCBkoko.isSelected()){
                        i += 80;                          
                    }
                    if(jCBjuhla.isSelected()){
                        i += 50;
                    }
                    if(jCBkoe.isSelected()){
                        i += 20;                          
                    }
                    if(jCBpesu.isSelected()){
                        i += 10;                          
                    }
                    if(jCBkiharrus.isSelected()){
                        i += 15;                          
                    }
                    if(jCBpermanentti.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jCBnetti.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Henkilömäärä " + maara + " " + "\n" + "Loppusumma: " + total + " €"); 
                }
                if("Lyhyet".equals(buttonGroup2.getSelection().getActionCommand())){
                    i = a + 0;                
                    if(jCBraidat.isSelected()){
                        i += 30; 
                    }
                    if(jCBtyvivari.isSelected()){
                        i += 30;     
                    }
                    if(jCBkoko.isSelected()){
                        i += 80;                          
                    }
                    if(jCBjuhla.isSelected()){
                        i += 50;
                    }
                    if(jCBkoe.isSelected()){
                        i += 20;                          
                    }
                    if(jCBpesu.isSelected()){
                        i += 10;                          
                    }
                    if(jCBkiharrus.isSelected()){
                        i += 15;                          
                    }
                    if(jCBpermanentti.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jCBnetti.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Henkilömäärä " + maara + " " + "\n" + "Loppusumma: " + total + " €"); 
                }
             
        }
        
        jList1.setModel(dlm);               
        
        
        if("Lapset".equals(buttonGroup1.getSelection().getActionCommand())) {
            a = 15;
                if("Keskipitkät".equals(buttonGroup2.getSelection().getActionCommand())){
                    i = a + 5;
                    if(jCBraidat.isSelected()){
                        i += 30; 
                    }
                    if(jCBtyvivari.isSelected()){
                        i += 30;     
                    }
                    if(jCBkoko.isSelected()){
                        i += 80;                          
                    }
                    if(jCBjuhla.isSelected()){
                        i += 50;
                    }
                    if(jCBkoe.isSelected()){
                        i += 20;                          
                    }
                    if(jCBpesu.isSelected()){
                        i += 10;                          
                    }
                    if(jCBkiharrus.isSelected()){
                        i += 15;                          
                    }
                    if(jCBpermanentti.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jCBnetti.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Henkilömäärä " + maara + " " + "\n" + "Loppusumma: " + total + " €"); 
                }
                if("Pitkät".equals(buttonGroup2.getSelection().getActionCommand())){
                    i = a + 10;
                    if(jCBraidat.isSelected()){
                        i += 30; 
                    }
                    if(jCBtyvivari.isSelected()){
                        i += 30;     
                    }
                    if(jCBkoko.isSelected()){
                        i += 80;                          
                    }
                    if(jCBjuhla.isSelected()){
                        i += 50;
                    }
                    if(jCBkoe.isSelected()){
                        i += 20;                          
                    }
                    if(jCBpesu.isSelected()){
                        i += 10;                          
                    }
                    if(jCBkiharrus.isSelected()){
                        i += 15;                          
                    }
                    if(jCBpermanentti.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jCBnetti.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Henkilömäärä " + maara + " " + "\n" + "Loppusumma: " + total + " €"); 
                }
                if("Lyhyet".equals(buttonGroup2.getSelection().getActionCommand())){
                    i = a + 0;                
                    if(jCBraidat.isSelected()){
                        i += 30; 
                    }
                    if(jCBtyvivari.isSelected()){
                        i += 30;     
                    }
                    if(jCBkoko.isSelected()){
                        i += 80;                          
                    }
                    if(jCBjuhla.isSelected()){
                        i += 50;
                    }
                    if(jCBkoe.isSelected()){
                        i += 20;                          
                    }
                    if(jCBpesu.isSelected()){
                        i += 10;                          
                    }
                    if(jCBkiharrus.isSelected()){
                        i += 15;                          
                    }
                    if(jCBpermanentti.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jCBnetti.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Henkilömäärä " + maara + " " + "\n" + "Loppusumma: " + total + " €");
                }
             
       
        
        jList1.setModel(dlm);     
                       

    
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
     DefaultListModel dlm2 = new DefaultListModel();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dlm2.addElement(jList1.getSelectedValue());
        jList2.setModel(dlm2);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T10kampaamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T10kampaamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T10kampaamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T10kampaamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T10kampaamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCBjuhla;
    private javax.swing.JCheckBox jCBkiharrus;
    private javax.swing.JCheckBox jCBkoe;
    private javax.swing.JCheckBox jCBkoko;
    private javax.swing.JCheckBox jCBnetti;
    private javax.swing.JCheckBox jCBpermanentti;
    private javax.swing.JCheckBox jCBpesu;
    private javax.swing.JCheckBox jCBraidat;
    private javax.swing.JCheckBox jCBtyvivari;
    private javax.swing.JLabel jLblPituus;
    private javax.swing.JLabel jLblhlo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JRadioButton jRbtAikuiset;
    private javax.swing.JRadioButton jRbtKeskipitkat;
    private javax.swing.JRadioButton jRbtLapset;
    private javax.swing.JRadioButton jRbtLyhyet;
    private javax.swing.JRadioButton jRbtPitkat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpnMaara;
    private javax.swing.JTextField jTxtFvalinnat;
    // End of variables declaration//GEN-END:variables
}
